**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/indexing-selecting-assigning).**

---

# Introduction

In this set of exercises we will work with the [Wine Reviews dataset](https://www.kaggle.com/zynicide/wine-reviews).

Run the following cell to load your data and some utility functions (including code to check your answers).

In [1]:
import pandas as pd

reviews = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
pd.set_option("display.max_rows", 5)

from learntools.core import binder; binder.bind(globals())
from learntools.pandas.indexing_selecting_and_assigning import *
print("Setup complete.")

Setup complete.

Look at an overview of your data by running the following line.

In [ ]:
reviews.head()

# Exercises

## 1.

Select the `description` column from `reviews` and assign the result to the variable `desc`.

In [4]:
# Your code here
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
reviews.head()
desc = reviews.loc[:,'description']

# Check your answer
desc

0         This tremendous 100% varietal wine hails from ...
1         Ripe aromas of fig, blackberry and cassis are ...
                                ...
150928    A perfect salmon shade, with scents of peaches...
150929    More Pinot Grigios should taste like this. A r...
Name: description, Length: 150930, dtype: object

Follow-up question: what type of object is `desc`? If you're not sure, you can check by calling Python's `type` function: `type(desc)`.

In [ ]:
#q1.hint()
#q1.solution()

## 2.

Select the first value from the description column of `reviews`, assigning it to variable `first_description`.

In [5]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
first_description = reviews.loc[0,'description']

# Check your answer
first_description

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

In [ ]:
#q2.hint()
#q2.solution()

## 3. 

Select the first row of data (the first record) from `reviews`, assigning it to the variable `first_row`.

In [6]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
first_row = reviews.iloc[:1]

# Check your answer
first_row

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz

In [ ]:
#q3.hint()
#q3.solution()

## 4.

Select the first 10 values from the `description` column in `reviews`, assigning the result to variable `first_descriptions`.

Hint: format your output as a pandas Series.

In [7]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
first_descriptions = reviews.loc[:9, 'description']

# Check your answer
first_descriptions

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
                           ...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, Length: 10, dtype: object

In [ ]:
#q4.hint()
#q4.solution()

## 5.

Select the records with index labels `1`, `2`, `3`, `5`, and `8`, assigning the result to the variable `sample_reviews`.

In other words, generate the following DataFrame:

![](https://storage.googleapis.com/kaggle-media/learn/images/sHZvI1O.png)

In [16]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
sample_reviews = reviews.loc[:,['country','description','designation','price','region_2']]

# Check your answer
sample_reviews

,country,description,designation,price,region_2
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,235.0,Napa
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,110.0,NaN
...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,52.0,NaN
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,15.0,NaN

In [ ]:
#q5.hint()
#q5.solution()

## 6.

Create a variable `df` containing the `country`, `province`, `region_1`, and `region_2` columns of the records with the index labels `0`, `1`, `10`, and `100`. In other words, generate the following DataFrame:

![](https://storage.googleapis.com/kaggle-media/learn/images/FUCGiKP.png)

In [20]:
# import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
df = reviews.loc[[0,1,10,100],['country','province','region_1', 'region_2']]

# Check your answer
q6.check()
df

Incorrect: Incorrect value for `df`

    country            province     region_1     region_2
0        US          California  Napa Valley         Napa
1     Spain      Northern Spain         Toro          NaN
10    Italy  Northeastern Italy       Collio          NaN
100      US          California  South Coast  South Coast

In [ ]:
#q6.hint()
#q6.solution()

## 7.

Create a variable `df` containing the `country` and `variety` columns of the first 100 records. 

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the tutorial:

> `iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. 
`loc`, meanwhile, indexes inclusively. 

> This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` return 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.iloc[0:999]`.

In [29]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
df = reviews.iloc[0:100,[1,9]]
dff = reviews.loc[:99,['country','variety']]

# Check your answer
df

   country               variety
0       US    Cabernet Sauvignon
1    Spain         Tinta de Toro
..     ...                   ...
98  France         Merlot-Malbec
99  France  Ugni Blanc-Colombard

[100 rows x 2 columns]

In [ ]:
#q7.hint()
#q7.solution()

## 8.

Create a DataFrame `italian_wines` containing reviews of wines made in `Italy`. Hint: `reviews.country` equals what?

In [35]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
italian_wines = reviews.loc[reviews.country.isin(['Italy'])]

# Check your answer
italian_wines

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
10,10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
32,32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
...,...,...,...,...,...,...,...,...,...,...,...
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [ ]:
#q8.hint()
#q8.solution()

## 9.

Create a DataFrame `top_oceania_wines` containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [34]:
import pandas as pd
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")
top_oceania_wines = reviews.loc[(reviews.country.isin(['Australia','New Zealand'])) & 
(reviews.points>=95)]

# Check your answer
top_oceania_wines

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
2148,2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck
2458,2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham
...,...,...,...,...,...,...,...,...,...,...,...
150562,150562,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,Shiraz,Penfolds
150563,150563,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,Shiraz,Penfolds

In [ ]:
#q9.hint()
#q9.solution()

# Keep going

Move on to learn about **[summary functions and maps](https://www.kaggle.com/residentmario/summary-functions-and-maps)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*